### PR TITLE
Unity Editor upgrade for MLagents version bump

### PR DESCRIPTION
**Pull request by benaslater**
** Note: ** This is the main PR out of 3 PRs in the mlagents upgrade. The other two can be found in python [here](https://github.com/Kinds-of-Intelligence-CFI/animal-ai-python/pull/10) and in the E2E package [here](https://github.com/Kinds-of-Intelligence-CFI/animal-ai-e2e/pull/2). All three should be reviewed and merged together

### PR Description

Our mlagents version had fallen behind, so this change bumps this in python and unity. This was beginning to cause issues, such as the stable baselines3 contrib not supporting the version of python we were stuck on.

Alongside this we also bump the python (to min 3.10.12) and unity editor versions (2.3.0-exp.3 to 2022.3.50f1) to bring them into line.

**When released this will be a breaking change, and so should include a major version bump**

There is still some testing which I can't do, which we should do before releasing.

### TODO

- Test Apple and Linux builds (I don't have access to machines of this type)
- Update documentation
- Unity unit tests
- Bump to latest Tech Stream 2023 version
- Long running test

### Proposed change(s)

Update mlagents version in python and unity codebases

### Useful links (Github issues, discussion threads, etc.)

Related to https://www.notion.so/Evaluate-ML-Agents-1-0-0-Upgrade-b9d30ca34fd24ea4996014dc06ed67a7?pvs=4

### Types of change(s)
- [ ] Bug fix
- [ ] New feature
- [ ] Code refactor
- [X] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

### Checklist
- [N/A (Updated existing tests)] Added tests that prove my fix is effective or that my feature works
- [N/A] Updated the changelog (if applicable)
- [TODO] Updated the documentation (if applicable)
- [N/A] Updated the migration guide (if applicable)

### Testing

- Ran E2E tests, and updated where necessary
- Play some arenas in play mode and ensure the experience is the same as 4.1.0
- Compare the log files created by the animalAI executable (i.e. Player0.log) in 4.1.0 and after the change to ensure there are no significant differences

### CODE REVIEW

**Comment by alhasacademy96** [comment]
### A few things before the actual review: update the PR description to include these details and information:

1. What Unity Editor version is being upgraded from and specify the new version (e.g., “Upgraded Unity Editor from 2021.3.21f1 to 2022.x.xxx”). Is it LTS or experimental? Did the project file change due to these changes? These need to be specified in this PR as they are fundamental. 
2. What are the changes required and implemented to use mlagents 3.0.0 on the unity side? I.e. did you update the mlagents package on unity via package manager or via git? You stated this in the description, but be specific and detail it here as I've had to assume.
3. What was rebuilt (if anything) when the AAI project loaded on the new editor version (such as core unity/c# files, i.e., assembly.csproj).
4. Did you train agents using the new build built from the new editor (testing the changes made unity-side)? Anything to report?
5. Have all unit tests from the previous editor version been rerun on the new editor and passed?
6. "There is still some testing which I can't do, which we should do before releasing." What does this mean? Be specific please (this is probably referring to the lack of access to Linux and macOS for testing on these operating systems as you've mentioned but it still needs to be mentioned here). You can install a linux distribution on your windows machine via WSL (https://learn.microsoft.com/en-us/windows/wsl/install). You can also package builds for each OS (windows, macOS and Linux) via unity editor under build settings (https://docs.unity3d.com/Manual/BuildSettings.html). You can run the e2e tests on these builds without the need for access to the OS, in combination with running unit tests on unity. This is for future reference but this time I will do these for you.

In general, you need to provide far more information than what is offered currently. I'm assuming you've followed the official guide on upgrading editor versions (https://docs.unity3d.com/Manual/UpgradeGuides.html, more specifically: https://docs.unity3d.com/Manual/UpgradeGuide20222.html). You need to provide what changes will occur (i.e. rendering, physics, or other core systems) when upgrading to the new editor, such as whether rendering pipelines have been changed, any deprecated technologies to note, new ones, etc, so we don't get surprised when using the new editor. 
These need to be detailed here :)

For testing, be specific:
1. What log files are you referring to? console logs or player logs? Build logs? Which ones...
2. You probably forgot to put here that you ran the unit tests (assuming you did), so this should be specified here too :)

nit: the checklist is slightly confusing: 
> "[N/A (Updated existing tests)] Added tests that prove my fix is effective or that my feature works"

--> what do you mean with this? What is N/A? Or did you add tests to prove your changes work? Or is it N/A for the "added tests..." statement? Or you simply updated the tests? Which ones? Why did you have to?

Lastly, in general, if you still need to do more work on the PR, make sure it's set as draft and not set to ready for review, as the PR should be completed already and no TODOs should be left before you ask for a review.

**Comment by benaslater** [comment]
Hi Ibrahim,

I've updated my initial comment based on your comments, please find my individual responses below:

> The PR name should be different as the unity engine upgrades are not mlagents dependent

I don't think I agree with this point. In particular it's not true that `this PR should be independent from mlagents python PR as the two technologies are separate`: I began by trying to update just mlagents on the python side, but that breaks the interface with Unity, so these changes need to be made together. Apologies if that sequence of events wasn't clear from this PR / other conversations we've had.

It's unfortunate that github doesn't let you group PRs across multiple repos, but because of that I've chosen this PR as the 'main' PR for the change. My intention in doing this change was to upgrade the mlagents version, so I think that's the most appropriate title. I do agree with your sentiment for commit messages; and hopefully my commit messages in this and other PRs are clear what specifically is getting changed where.

> What Unity Editor version is being upgraded from and specify the new version

The new version is `2022.3.50f1`

> What are the changes required and implemented to use mlagents 3.0.0 on the unity side? I.e. did you update the mlagents package on unity via package manager or via git?

I manually updated the version of just `com.unity.ml-agents` in `manifest.json` (first commit) and then let unity do the rest (second commit)

> What was rebuilt (if anything) when the AAI project loaded on the new editor version (such as core unity/c# files, i.e., assembly.csproj)

See the second commit of this PR https://github.com/Kinds-of-Intelligence-CFI/animal-ai-unity/pull/44/commits/c35a91ee7384362684b20dfb7d7ef25714058a30

> Did you train agents using the new build built from the new editor (testing the changes made unity-side)? Anything to report?

I didn't train agents - the `testing the changes made unity-side` was running the E2E tests. As this uses the same interface training agents I don't think it would be exercising any code that's not being exercised already.

> Have all unit tests from the previous editor version been rerun on the new editor and passed?

Aah this is a miss from me, I'll do that! (may have to catch you for a quick call on the optimal way to run them)

> "There is still some testing which I can't do, which we should do before releasing." What does this mean?

This sentence was referring to the first TODO, as you've correctly inferred.

> You can install a linux distribution on your windows machine via WSL (https://learn.microsoft.com/en-us/windows/wsl/install).

Good point re linux: presumably the macOS distribution is still going to be an issue, or is there also a way of running that on a windows machine?

>In general, you need to provide far more information than what is offered currently. I'm assuming you've followed the official guide on upgrading editor versions (https://docs.unity3d.com/Manual/UpgradeGuides.html, more specifically: https://docs.unity3d.com/Manual/UpgradeGuide20222.html). You need to provide what changes will occur (i.e. rendering, physics, or other core systems) when upgrading to the new editor, such as whether rendering pipelines have been changed, any deprecated technologies to note, new ones, etc, so we don't get surprised when using the new editor.
These need to be detailed here :)

I downloaded the latest LTS version and it 'just worked' - happy to have a call to go through the docs and figure out specifics if you think it's necessary

> What log files are you referring to? console logs or player logs? Build logs? Which ones...

I'm referring to the log files created by the animalAI executable (i.e. Player0.log)

> You probably forgot to put here that you ran the unit tests (assuming you did), so this should be specified here too :)

Sadly no; I've added to my TODO list for now

> what do you mean with this? What is N/A? 

N/A = Not applicable: I didn't make any new tests. I did have to update a few though so thought it was worth mentioning here.

> Or did you add tests to prove your changes work? Or is it N/A for the "added tests..." statement? Or you simply updated the tests? Which ones? Why did you have to?

See https://github.com/Kinds-of-Intelligence-CFI/animal-ai-e2e/pull/2 for all these answers and more

> Lastly, in general, if you still need to do more work on the PR, make sure it's set as draft and not set to ready for review, as the PR should be completed already and no TODOs should be left before you ask for a review.

I don't agree with this. It's right that it's usually not worth sending partial work out for review, but in this case the only things remaining were testing you've offered to do and a documentation update, so the substantive work had already been completed. Getting the change out there allows reviewers to flag potential issues earlier: exactly this has happened in this review when you've flagged I missed running unity unit tests.

**Comment by alhasacademy96** [comment]
Hey Ben,

> The PR name should be different as the unity engine upgrades are not mlagents dependent
> I don't think I agree with this point. In particular it's not true that `this PR should be independent from mlagents python PR as the two technologies are separate`: I began by trying to update just mlagents on the python side, but that breaks the interface with Unity, so these changes need to be made together. Apologies if that sequence of events wasn't clear from this PR / other conversations we've had.

Unity engine editor upgrades are not dependent on ML-Agents. However, ML-Agents does depend on Unity since it’s a tool designed specifically for the Unity engine. This is why upgrading the Unity editor should be considered a standalone effort and shouldn’t be primarily framed as a means to update ML-Agents. When upgrading editor versions, especially over a span of a few years, many changes can occur. Therefore, the focus should extend beyond simply meeting the compatibility needs of ML-Agents—think about the long-term benefits of upgrading the engine itself. This isn’t a criticism, but I want to emphasize the importance of considering the broader impact of game engine upgrades, rather than just fulfilling the requirements of a specific tool.

> > What Unity Editor version is being upgraded from and specify the new version
> 
> The new version is `2022.3.50f1`

In our situation, we’re upgrading to ML-Agents 3.0.0, which requires upgrading the Unity editor to a minimum version of 2023.x.xxxx, not 2022.3.50f1. Please review the ML-Agents documentation/releases page again Ben, as it clearly specifies that the minimum Unity editor version is 2023, not 2022: [ML-Agents release page](https://github.com/Unity-Technologies/ml-agents/releases/tag/release_22). Why not unity 6 (the latest significant engine version)? Why the latest LTS version? You need to provide reasons for such decisions. 

> Did you train agents using the new build built from the new editor (testing the changes made unity-side)? Anything to report?
>
> I didn't train agents - the `testing the changes made unity-side` was running the E2E tests. As this uses the same interface training agents I don't think it would be exercising any code that's not being exercised already.

While it is true that E2E tests can exercise many aspects of the same interface used during training—there might still be differences between running E2E tests and actual agent training. Importantly, ttraining agents could uncover performance issues, stability problems, or other bugs specific to long training sessions that might not surface in E2E tests. Also, the E2E tests are still not adequate enough to conclude everything just works. It's just a bit more work to do and shouldn't take too much time to carry out.

Other minor comments:

1. I'm not sure you can simulate macOS on windows. I will carry this out for you, including Linux(Ubuntu is distro I use). 
2. Regarding the checklist, I got confused on what was N/A, not the meaning of it. But it's clarified now. 
3. I don't mind waiting a bit longer for you to do the rest of the TODO's as they are important.

Theres still a few important things to do here so keep going!

**Comment by benaslater** [comment]
> Why not unity 6 (the latest significant engine version)? Why the latest LTS version? You need to provide reasons for such decisions.

hmm just generally I would go for the latest LTS version since it's the one the company has actually committed to supporting. I'm a little surprised it built at all, and that they don't have some way of making Unity just throw because the editor version isn't new enough.

If not LTS, I wouldn't go for Unity 6 - their versioning is a bit weird but I guess 2023.x -> 6.x is a major version bump, so would make this change more risky (also they're still calling it "Unity 6 preview" on https://unity.com/releases/unity-6). So given all that I suppose the sensible choice is the latest Tech Stream 2023.x release. I'll rebuild with that and update this PR.

> training agents could uncover performance issues, stability problems, or other bugs specific basic/sophisticated training sessions that might not surface in E2E tests

Yeah that's fair, I can train something in the background just to make sure it works. Seems like we need a long running E2E test....

**Comment by alhasacademy96** [comment]
Getting unity 6 as opposed to an earlier version would not be risky if done right and handled appropriately. Unity 6 will be released 17 October 2024 (today). Since you upgraded to the wrong editor version in the first place, why not experiment with a few editor versions? Remember this editor version upgrade is done rarely in a game project's dev cycle, so it would make sense to spend a good amount of time and effort to experiment with a few editor versions and evaluate their cons/pros for AAI. 

I am also strongly opinionated to changing the PR title to something else, probably a compromise would be " unity editor version upgrade from xxxx.x.xxxx to yyyy.y.yyyy for mlagents upgrade requirement" or something like that. 

let me know if you need a call!!!

**Comment by alhasacademy96** [comment]
Hey Ben. Straight to the points:

> > Simply choosing the minimum year and latest lts just because isn't the correct approach
> 
> I don't agree with your suggestion that I chose to move to the latest LTS version "just because". In general LTS versions are good to go for because they're the ones that the company has committed to maintaining: if there's an issue with an LTS version we're much more likely to get a fix. Unity calls it "The release for creators who value maximum stability and support for their next project" [here](https://unity.com/releases/lts-vs-tech-stream).

What I meant here was that because, say version 2023, has multiple LTS versions, why did you choose the latest LTS? Why not the previous one or the first LTS for 2023? What's the difference between these versions you found after your research, and why did you go for the latest LTS for 2023? These are all LTS versions, so they have long-term-support anyway, regardless of when they were released. It's a tricky slope to assume that "newer is better", especially in game development.

> I feel like I'm looping on my previous comment a bit, but it seems as though there's a reliance on a feature only in the tech stream version somewhere in mlagents. I'm suggesting as a next step I should update this PR to use the latest tech stream version, in spite of the fact that an LTS version would have been more stable.

Why would this be the case? According to this logic, the latest tech stream would be unity 6, as unity would focus on unity 6 to make it more stable, to improve on it. All of the LTS versions are stable. What is not stable is experimental or preview versions, for obvious reasons. 

However, as you've requested to take this task, I will leave it to you to decide on which editor version we will upgrade to (provided you present your reasons for the chosen editor version). This will assume you did all the research to make an informed and calculated decision. There is no time limitation here as I am working on other aspects of the project in the meantime (theres still testing to do for the PR I'm working on). I think a few more days wouldn't hurt to make an informed decision here Ben. This goes back to the comment I made earlier that upgrading a game engine version should be standalone and not for the sole reason of bumping mlagents. Yes, we would require to do this but we should focus on other aspects of this process also, i.e., how AAI would be impacted technically going forward. 

> > Since you upgraded to the wrong editor version in the first place, why not experiment with a few editor versions?
> 
> Time constraints mostly, but also my intention is to upgrade mlagents which has required an editor version bump so I'm happy with a new editor version that is 'better' if not necessarily 'best'.

I think from a development point of view, this is a bad reason to state. If AAI was a commercial product (as a real-world example would dictate), it would be a costly endeavour, financially and technically. It's also equally bad to state even though AAI isn't commercial, as the project could be implicated down the line, in the future (AAI has limited funding now, so we need to make careful technical decisions). 

> > Remember this editor version upgrade is done rarely in a game project's dev cycle, so it would make sense to spend a good amount of time and effort to experiment with a few editor versions and evaluate their cons/pros for AAI
> 
> Perhaps we could do this in a separate change before the future AAI release with a major version bump, but I think that activity should be beyond the scope of this change for reasons I mention above.
> 
> Although I'm not sure that, for the animalAI project, it has to be the case that the editor version is changed very rarely. From my experience just doing this one it was quite painless.

Yeah it's of course feasible to upgrade frequently, but it would cost time and effort, which AAI has limited funds for currently. It's just also not standard to follow this approach as upgrading engine versions requires substantial need and the benefits must outweigh the cons (I know this as I have experienced this in the hard way for my own game, which resulted in many hours of debugging and getting the game working on the new engine version). 

P.S. Sorry if it seems like im grinding you but this is an important PR and the responsibility rests on me as you have no experience in game engines or game development, so im trying to help you as much as I can and teach you a few things along the way in this regard :)

**Comment by alhasacademy96** [comment]
Closed this PR as it's not compatible and needs significant rework. New PR will be reworked from the ground up to implement the same changes. @benaslater

**Pull request closed without merging**
